name: Build Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # Можно оставить latest!
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Очистка кэша от прошлых запусков
      - name: Clean previous build
        run: |
          rm -rf .buildozer bin dist

      # Установка зависимостей только для работы с Git и Docker
      - name: Install system dependencies and classic Docker
        run: |
          sudo apt-get update && sudo apt-get upgrade -y

          # Устанавливаем утилиты для ключей
          sudo apt-get install -y ca-certificates curl gnupg lsb-release

          # Добавляем GPG-ключи Docker-а
          sudo mkdir -m 0755 -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

          # Добавляем официальный репозиторий Docker-а
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

          # Обновляем пакеты после добавления нового реп
