name: Build Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # Можно оставить latest, теперь это не важно!
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Очистка кэша от прошлых запусков
      - name: Clean previous build
        run: |
          rm -rf .buildozer bin dist

      # Установка зависимостей только для работы с Git и Docker
      - name: Install system dependencies
          # Установка Git и современного менеджера контейнеров для Ubuntu 24.04
        run: |
              # Обновляем список пакетов
              sudo apt-get update
            
              # Устанавливаем Git
              sudo apt-get install -y --no-install-recommends git
            
              # Удаляем старые остатки Docker, если они есть
              sudo apt-get remove -y docker docker-engine containerd runc || true
            
              # Устанавливаем nerdctl (современный аналог Docker)
              sudo snap install nerdctl --classic

      # Запуск официальной среды python-for-android внутри контейнера
      - name: Build APK in official P4A container
        env:
          ANDROID_API: 33         # Целевая версия API
          ANDROID_MINAPI: 24      # Минимальная поддерживаемая версия
          DIST_NAME: passgen      # Название дистрибутива из spec-файла
          REQUIRES: python3,kivy  # Зависимости из spec-файла
          BOOTSTRAP: sdl2         # Бутстреп из spec-файла
          ARCHS: arm64-v8a,armeabi-v7a,x86_64 # Архитектуры (можно убрать x86_64)
        run: |-
          # Создаем папку для сохранения результатов
          mkdir -p artifacts

          # Собираем контейнером
          nerdctl run --rm \
            -e PACKAGES_PATH=/packages \
            -e ANDROIDSDK=/android-sdk \
            -e 
